version: '3.8'

services:
  spring-api:
    image: adilinan/spring-api-pzn:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restapi
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: psql123
      NEW_RELIC_APP_NAME: spring_api_net
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: restapi
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: psql123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U springuser"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:

networks:
  app-network:
