services:
  spring-api:
    image: adilinan/spring-api-pzn:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restapi
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: psql123
      NEW_RELIC_APP_NAME: spring_api_net
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: restapi
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: psql123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
