name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

env:
  DOCKER_IMAGE_NAME: adilinan/spring-api-pzn
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven (skip test)
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEW_RELIC_LICENSE_KEY=${{ env.NEW_RELIC_LICENSE_KEY }} \
            --build-arg SENTRY_DSN=${{ env.SENTRY_DSN }} \
            -t ${{ env.DOCKER_IMAGE_NAME }}:latest \
            .
    

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:latest
